### ISSUE TITLE
veth 插件 参数 

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/cni-plugins#1]
![企业微信截图_5831d3bc-4d74-4731-a453-da88e11ba487](https://user-images.githubusercontent.com/45163302/187168111-71f0a186-90b2-4517-b178-e38aff4a9410.png)

**Comment by cyclinder** [comment]
1. 建议保留dst结构，使用原来结构最大程度与社区保持一致。另外可省去IP格式的校验。
2. skip的原意是 可选择跳过 此plugin的执行，可改为skip_call,默认为false

**Comment by weizhoublue** [comment]
建议保留dst结构，使用原来结构最大程度与社区保持一致。另外可省去IP格式的校验。 
-----
不建议保留，这个书写太麻烦，用户体验不好，且 根本不会写 下跳，它的语义不是一个路由了，而是劫持哪些子网
