### ISSUE TITLE
macvlan 增强调度

### ISSUE THREAD

**Issue by gssjl2008** [spidernet-io/cni-plugins#107]
**What would you like to be added**:
macvlan 会调度到任意节点，不同节点master 接口名称可能不一致，如何规避调度问题

同理，所以节点可能不在同一个子网上，macvlan 使用一张卡的情况下，也可能会调度不同子网节点上，如何规避调度问题
**Why is this needed**:

**Comment by cyclinder** [comment]
这个目前只能从 pod 调度方面来规避，必须保证 节点上有 macvlan 的master 接口

目前 multus 也不能做到 其crd 有 nodeSelector,  不同master 节点的接口不一样是否是常见case? 我看灵雀云使用underlay 必须要保证每个节点有相同的接口

**Comment by cyclinder** [comment]
调度使用原生的 nodeSelector 即可
