### ISSUE TITLE
主机接口使用说明

### ISSUE THREAD

**Issue by gssjl2008** [spidernet-io/cni-plugins#109]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/43020699/204199663-6837b6f6-435a-4c12-8c88-46b799b64694.png">
希望能多加一些使用方面的说明， 这些细节问起来，比较头疼。

**Comment by cyclinder** [comment]
/assign @cyclinder 

回头给个结论，输出产品文档

**Comment by cyclinder** [comment]
e2e文档已输出
