### ISSUE TITLE
优化镜像名

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/cni-plugins#14]
可把 arm 和 amd 整合一个镜像名字

**Comment by cyclinder** [comment]
不用区分arm64和amd64?

**Comment by weizhoublue** [comment]
我也看很多项目不用 带 arm 的镜像 都能工作，只是他们额外提供了 arm 等 tag的 镜像而已
镜像名本身名字是什么，并不影响 镜像拉取，它取决于 镜像manifest
而这个不同名字会给 部署参数带来 区分，增加出错概率

**Comment by cyclinder** [comment]
fixed in https://github.com/spidernet-io/cni-plugins/pull/28

/closed
