### ISSUE TITLE
calico ipip模式，macvlan pod ping跨节点主机不通

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/cni-plugins#150]
**What happend**:
calico ipip模式，macvlan pod ping跨节点主机不通

**Anything else we need to know?**:
pod的100表缺少main路由表的一个条目
<img width="356" alt="企业微信截图_16735783982222" src="https://user-images.githubusercontent.com/86399306/216220363-99898857-6faa-49b5-933f-a857e0d500f8.png">
<img width="402" alt="企业微信截图_16735785763279" src="https://user-images.githubusercontent.com/86399306/216220392-b11ef8b3-a55a-4a87-9c87-4c260fdc9054.png">

**Comment by cyclinder** [comment]
/close

原因是pod的cidr 与节点冲突了，导致pod回包匹配策略路由，导致的问题
