### ISSUE TITLE
there are some typos in advanced usages

### ISSUE THREAD

**Issue by liyuerich** [spidernet-io/cni-plugins#166]
there are some typos in advanced usages
https://github.com/spidernet-io/cni-plugins/blob/main/docs/usage/advance.md

1 please refer this screenshot
![image](https://user-images.githubusercontent.com/97269208/222136180-0eefa52b-942a-448e-95f0-e108a668966e.png)

2 please refer this screenshot
![image](https://user-images.githubusercontent.com/97269208/222137639-65c11480-e2ec-4ac7-bf33-3d5c792945cb.png)

**Comment by cyclinder** [comment]
It looks like you don't have permission to label issue. I will remove this limitation later. And thanks for your report! @liyuerich 

Can you take a look at this?  @ii2day
/kind doc
/assign @ii2day
