### ISSUE TITLE
2个 chart 小bug

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/cni-plugins#19]
![wecom-temp-04f7def21966bdac3324b1e25eb8a614](https://user-images.githubusercontent.com/45163302/187700297-b6a7d8cf-a435-42ae-92a6-9ef9e1201a83.png)
![wecom-temp-b0bce7ea8886ea04644dff56e8f4f633](https://user-images.githubusercontent.com/45163302/187700313-399f9a19-c5af-42af-b9ed-5f8e88513101.png)

**Comment by cyclinder** [comment]
fixed.
