### ISSUE TITLE
macvlan-overlay环境联通性

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#37]
110主机上curl，120主机V6IP+nodeport
![image](https://user-images.githubusercontent.com/31728060/192950408-f38306fd-9283-401a-a5fb-20630b3a955c.png)
https://dwiki.daocloud.io/pages/viewpage.action?pageId=132761288
确认是已知问题

**Comment by cyclinder** [comment]
overlay 场景下，pod 与 主机 之间 ipv6 通讯有问题， 跨节点正常。
