### ISSUE TITLE
【现象】macvlan-overlay pod起不来，报cannot unmarshal array into Go struct field PluginConf.routes

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#39]
![image](https://user-images.githubusercontent.com/31728060/192951491-e9c8db78-6b59-4535-8675-12aebdeea5ff.png)
1 multus-underlay装好，macvlan-overlay实例装好
2 pod annotation打好

**Comment by cyclinder** [comment]
不是bug, 二进制 bin 的版本 和 crd 配置的版本对应不上造成的问题
