### ISSUE TITLE
安装multus-underlay，kube-meta-plugins-ds为自动创建的，界面上无法输入版本号，而创建出来的kube-meta-plugins-ds并不是latest版本

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#40]
【现象】创建macvlan-overlay的应用起不来，报如图
![企业微信截图_22b9b26a-f1a1-4e90-9e6f-0b91750a4f89](https://user-images.githubusercontent.com/31728060/192952038-2f2d533f-4e56-498a-baa0-f7dd434fb60f.png)
【配置】
pod annotation
![企业微信截图_ab6e577c-6eab-49be-bd0b-46029d7111a3](https://user-images.githubusercontent.com/31728060/192952084-3818d751-319b-49dc-bdfc-73a9cf47d485.png)
【解决】
更新meta-plugins版本为latest
【期望】
kube-meta-plugins-ds为自动创建的，界面上无法输入版本号，而创建出来的kube-meta-plugins-ds并不是latest版本
![企业微信截图_74f8f534-3ada-4929-b88e-430c89746f0f](https://user-images.githubusercontent.com/31728060/192952146-e0feb4bc-9bc7-4278-9e5a-7a17278ae567.png)

**Comment by cyclinder** [comment]
这个是刻意而为之，子 chart 的镜像的版本默认跟着 chart 的版本走。
