### ISSUE TITLE
add test case 1000 pods create,restart,scale,delete,cluster restart to time cost

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#42]
add test case:
1000 pods create,restart,scale,delete,cluster restart  to time cost

**Comment by cyclinder** [comment]
dup with https://github.com/spidernet-io/cni-plugins/issues/43, 

增加测试范围

**Comment by cyclinder** [comment]
这个只能手工测试,关闭这个因和https://github.com/spidernet-io/cni-plugins/issues/152重复

/close
