### ISSUE TITLE
add test case:jmeter对cluster ip/nodeport并发curl 1000/s

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#43]
add test case: jmeter对cluster ip/nodeport并发curl 1000/s

**Comment by cyclinder** [comment]
这应该不属于 该项目的范畴

**Comment by cyclinder** [comment]
这个只能手工测试,关闭这个因和https://github.com/spidernet-io/cni-plugins/issues/152%E9%87%8D%E5%A4%8D

/close
