### ISSUE TITLE
macvlan standalone双卡 与calico pod ip不通

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#50]
【现象】：macvlan standalone双卡 与calico pod ip不通
【环境】10.6.158.66
<img width="968" alt="企业微信截图_3836e8aa-fa58-48ce-8dc4-85a90ac9ed65" src="https://user-images.githubusercontent.com/31728060/195789943-4053328a-9429-4949-94d4-ff813ee6ad4d.png">
 分析：ip r
<img width="823" alt="企业微信截图_5ea34a96-f899-4a11-9193-a0428b6d4e9b" src="https://user-images.githubusercontent.com/31728060/195790027-6113520a-abc4-4816-9e31-eda65ee1ac15.png">
步骤：
1 创建的是standalone的双卡工作负载
 pod annotation
ipam.spidernet.io/ippools:
[{"interface":"eth0","ipv4pools": ["default-v4-ippool"]}, {"interface": "net1","ipv4pools": ["10-7-0-1"]}]
k8s.v1.cni.cncf.io/networks:kube-system/macvlan-standalone-aa
v1.multus-cni.io/default-network:kube-system/macvlan-standalone-vlan0
2  进入66主机上的pod，ping 68主机上的calico pod,不通
<img width="618" alt="企业微信截图_9134a600-f400-4091-b577-a2413e06427d" src="https://user-images.githubusercontent.com/31728060/195790866-c7646bf4-6c33-46bb-85c2-f386f4cd33a8.png">
66 这个节点上ping 68上的calico pod是通的
进入66节点上的pod中，ping 68上的calico pod是不通的

期望
standalone 不强求与calico 通讯，但应该可以通

**Comment by cyclinder** [comment]
macvlan-standalone 场景 期望 只与 macvlan pod通讯， 不强求与 calico等overlay cni通讯。但其实我们是支持可以通讯，这个我测试验证过，应该是你环境中 calioc pod通讯就有问题

**Comment by cyclinder** [comment]
问题未复现，如果再遇到问题再 /reopen 吧

/close
