### ISSUE TITLE
https://docs.daocloud.io中没有解释选择macvlan-vlan0的用法

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#51]
安装multus-underlay界面选择如图
![企业微信截图_2b58c952-ba18-4963-bdbb-c42af9cfeb17](https://user-images.githubusercontent.com/31728060/195827418-5cfc7283-985b-4cf6-a066-27b5b85f1366.png)
在下面的文档中没有有关macvlan-vlan0的解释
有macvlan-standalone和macvlan-overlay的
https://docs.daocloud.io/zh/network/modules/multus-underlay/install/#_4

**Comment by cyclinder** [comment]
macvlan-vlan0只是默认的名字，解释都在 macvlan-type 中
