### ISSUE TITLE
macvlan-overlay的pod中curl clusterip+80和curl ep+80的ipv6地址时通时不通

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#61]
【环境】10.6.168.131
进入overlay的pod，名称daoyw
curl nginx的cluster ip+80 有时不通
curl "http://\[fd85:ee78:d8a6:8607::1001\]:80"

curl nginx的另一台主机上nginx endpoit+80不通，本机nginx pod通的
curl "http://\[fd85:ee78:d8a6:8607::1:eb98\]:80"

curl nginx的对端主机+nodeport不通，本机也不通
curl "http://\[fd00:6::10:6:168:131\]:32666"

以上在168.131节点上都能通，进入overlay pod不通
![image](https://user-images.githubusercontent.com/31728060/196153600-09ae76e1-c669-49cc-9687-00deebc16929.png)

【分析】
calico 自身ipv6通讯有问题，calico  pod ipv6跨节点不通

**Comment by cyclinder** [comment]
calico 自身 ipv6通讯有问题：https://github.com/projectcalico/calico/issues/6877
