### ISSUE TITLE
sriov-overlay ping对端主机不通；curl 对端主机+nodeport不通

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#64]
【现像】sriov-overlay ping对端主机不通；curl 对端主机+nodeport不通
【环境】172.17.8.110
【配置】在容器组注解中加入例如：
[ipam.spidernet.io/ippool](http://ipam.spidernet.io/ippool):{ "interface": "net1", "ipv4pools": [ "default-v4-ippool" ], "ipv6pools": [ "default-v6-ippool" ]}
[k8s.v1.cni.cncf.io/networks](http://k8s.v1.cni.cncf.io/networks):kube-system/sriov-overlay-vlan82
【CRD】
![image](https://user-images.githubusercontent.com/31728060/196658357-8feb263d-4898-4f52-9453-008993c8fbfd.png)
【步骤】
1 srv-over pod运行成功
2 进入这个pod
3 ping 172.17.8.120不通
ping fd00:1033::172:17:8:120不通
curl http://172.17.8.120:31696/不通
curl "http://\[fd00:81::172:17:8:120\]:32658"不通

**Comment by cyclinder** [comment]
vlan82 对应的ip池 请用 vlan82 段
```
root@172-17-8-110:~# kubectl get sp | grep vlan82
172-82-vlan82       4         172.82.0.0/16    2                    91               false
172-82-vlan82-v6    6         fd00:82::/64     2                    48               false
```

**Comment by yulng** [comment]
> vlan82 对应的ip池 请用 vlan82 段
> 
> ```
> root@172-17-8-110:~# kubectl get sp | grep vlan82
> 172-82-vlan82       4         172.82.0.0/16    2                    91               false
> 172-82-vlan82-v6    6         fd00:82::/64     2                    48               false
> ```

刚换成82的了，还是不通
![image](https://user-images.githubusercontent.com/31728060/196668951-51721e50-15e6-46f7-9143-d8eaa5a630b3.png)

**Comment by cyclinder** [comment]
应该跟交换机配置有关

**Comment by cyclinder** [comment]
确认是交换机配置有关，vf配置vlan后发出的数据包都带有 vlan tag，而对端主机地址不带tag，自然不通
