### ISSUE TITLE
cilium是否考虑做underlay？ from 王钟汉 （售前）

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#71]
cilium是否考虑做underlay？

**Comment by yulng** [comment]
> cilium是否考虑做underlay？
underlay 网络 networkpoliy会依赖于 cilium  来做

**Comment by cyclinder** [comment]
此插件开发时就注意与calico 或 cilium 进行搭配，所以是支持的，但需要后续验证
