### ISSUE TITLE
macvlan 如何做到网络策略的限制？ from 陈沈 （交付）

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#72]
macvlan 如何做到网络策略的限制？

**Comment by yulng** [comment]
> macvlan 如何做到网络策略的限制？

结合 cilium 进行实现？ Peter：macvlan没有网络策略能力

**Comment by cyclinder** [comment]
macvlan 本身没有网络策略能力，更多依赖与真实网络的防火墙策略
