### ISSUE TITLE
macvlan 方案在dce3的时候存在ip泄漏，残留，dce5 如果还用maxvlan方案，是否有对应的解决方案？from 朱争光（交付）

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#73]
macvlan 方案在dce3的时候存在ip泄漏，残留，dce5 如果还用maxvlan方案，是否有对应的解决方案？不然感觉影响比较大

**Comment by yulng** [comment]
> macvlan 方案在dce3的时候存在ip泄漏，残留，dce5 如果还用maxvlan方案，是否有对应的解决方案？不然感觉影响比较大

此macvlan非彼macvlan

**Comment by cyclinder** [comment]
ip泄漏更多与ipam有关，5.0 macvlan将于 spiderpool 搭配，spiderpool自身会注意ip泄漏的问题

**Comment by zgfh** [comment]
建议了解下老版本的泄露：如比较常见的macvlan网卡增加后，会加入到pod ns，目前怀疑是删除pod的时候，ns删除了，网卡没删除，导致ip再也无法回收了 @cyclinder

**Comment by cyclinder** [comment]
@zgfh 我可能不那么了解 3.0 macvlan，它应该是结合了我们自研代码， ip泄漏的问题跟 自研代码中有些并发问题导致，虽然都是macvlan，但5.0 跟 3.0的有些一样  :

- 首先这是完全开源方案，ns 的管理全部由开源 macvlan 或 cri 控制，我们不参与 ns的添加和删除
- 我们的插件最多只是会创建一对veth设备(没有IP地址)还有一些路由表之类的。当 ns 被删除，这些ns内的东西都会被删除，这是验证过的
-  另外 IP泄漏也跟 ipam 有关，我了解 spiderpool 本身有 gc 机制，是可以回收 泄漏的IP的
