### ISSUE TITLE
希望dce5也能安装的时候全部模式都支持，用的时候选择即可（交付）

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#76]
目前安装的时候要选择Macvlan Type，dce4其实是都支持，在用的时候配置即可，希望dce5也能安装的时候全部模式都支持，用的时候选择即可

**Comment by cyclinder** [comment]
这个本来是支持的，只是安装时ui隐藏了

**Comment by cyclinder** [comment]
这个不需要插件项目任何改动，修改下 multus-underlay chart 就可以了，目前的处理是界面隐藏了

**Comment by cyclinder** [comment]
只是节面隐藏，不影响使用

/close
