### ISSUE TITLE
cilium环境macvlan-overlay pod起不来

### ISSUE THREAD

**Issue by yulng** [spidernet-io/cni-plugins#84]
【现象】cilium环境macvlan-overlay pod起不来
【环境】10.6.178.71 
【配置】
1 cilium做为默认cni，pod可以分配ip成功
![企业微信截图_e5d6de77-28c5-4a6e-bc53-028febb83e85](https://user-images.githubusercontent.com/31728060/199216106-93268788-2912-4f1a-aff2-47661e0dd3e9.png)
2 spiderpool的subnet功能关闭
3 自建ippool:
![企业微信截图_3e4a5dfd-f53a-4370-9cc4-571ebfa0a5d0](https://user-images.githubusercontent.com/31728060/199216136-451b38ca-eea5-482e-9dc7-a24fe98c64ff.png)
4 pod annotation
![企业微信截图_9e8c0355-bf48-4435-a8e9-00e87cc40db6](https://user-images.githubusercontent.com/31728060/199216183-07f55251-f597-4ab9-9938-4b055c616c02.png)
5 macvlan-overlay crd
![企业微信截图_fffbe565-1118-42cb-8c86-5e6ed087f2aa](https://user-images.githubusercontent.com/31728060/199216220-719ac4b8-c6c1-4ee3-8c3d-6daf0ea93623.png)

6 macvlan-overlay pod报错：
![企业微信截图_94356799-cb3b-4fd4-b1e2-6c3fb9f383a7](https://user-images.githubusercontent.com/31728060/199216265-14dae1a1-f53c-4ad6-be47-9b68079fa403.png)

**Comment by weizhoublue** [comment]
annotations 写错了，看 spiderpool 最新文档

**Comment by yulng** [comment]
ipv4pools改为ipv4,pod起来，但是curl [http://10.233.38.35:80]不通

**Comment by yulng** [comment]
> ipv4pools改为ipv4,pod起来，但是curl [http://10.233.38.35:80]不通

说是cilium本身通讯问题
